#! /usr/bin/dh-exec
etc/bazel/bazelrc
usr/share/bazel/A-server.jar
usr/share/bazel/build-label.txt
usr/share/bazel/builtins_bzl/*
usr/share/bazel/install_base_key
usr/share/bazel/platforms/*
usr/share/bazel/embedded_tools/tools/build_defs/pkg/README.md => usr/share/doc/bazel-bootstrap/README-build_defs.md
usr/share/bazel/embedded_tools/tools/config/README.md => usr/share/doc/bazel-bootstrap/README-config.md
usr/share/bazel/embedded_tools/third_party/def_parser/Copyright.txt => usr/share/doc/bazel-bootstrap/def_parser-copyright.txt
usr/share/bazel/embedded_tools/*
